#!/usr/bin/env python3
"""Index this repository's own field notes (knowledge/**/*.md) into data/local-notes.json and knowledge/INDEX.md.

usage: index_local_notes.py [--repo-root DIR]
Front matter is a simple `key: value` block (lists as JSON, e.g. ["a","b"]); the same keys as universal-modder's template,
so a note can be offered upstream unchanged (only with the user's approval). Notes are validated: required keys, a Gotchas
section, no fenced code block over 150 lines, no obvious secrets. Exit code 1 on a validation failure."""
import argparse, json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
REQUIRED = ('kind', 'title', 'status', 'agents', 'date')
BASE = 'https://github.com/madpai/game-decomp-compendium/blob/main/knowledge/'

def parse(text):
    m = re.match(r'---\n(.*?)\n---\n', text, re.S)
    if not m: return None, text
    fm = {}
    for line in m.group(1).splitlines():
        if not line or line.startswith((' ', '#', '-')): continue
        k, _, v = line.partition(':'); v = v.strip()
        if v[:1] in '[{"':
            try: v = json.loads(v)
            except ValueError: v = v.strip('"')
        elif v[:1] == "'" : v = v.strip("'")
        fm[k.strip()] = v
    return fm, text[m.end():]

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--repo-root', default=os.path.normpath(os.path.join(HERE, '..', '..', '..', '..'))); a = ap.parse_args()
    kd = os.path.join(a.repo_root, 'knowledge'); notes = []; bad = []
    for dp, _, fs in os.walk(kd):
        for f in sorted(fs):
            if not f.endswith('.md') or f in ('README.md', 'INDEX.md', 'TEMPLATE.md'): continue
            p = os.path.join(dp, f); rel = os.path.relpath(p, kd)
            text = open(p, encoding='utf-8').read(); fm, body = parse(text)
            if fm is None: bad.append(f'{rel}: no front matter'); continue
            for k in REQUIRED:
                if k not in fm: bad.append(f'{rel}: missing {k}')
            if '## Gotchas' not in body: bad.append(f'{rel}: no Gotchas section')
            for blk in re.findall(r'```.*?\n(.*?)```', body, re.S):
                if blk.count('\n') > 150: bad.append(f'{rel}: code block over 150 lines')
            if re.search(r'(ghp_|gho_|AKIA[0-9A-Z]{12}|api[_-]?key\s*[:=]\s*\S{12,})', text, re.I): bad.append(f'{rel}: possible secret')
            summ = re.search(r'^>\s*(.+(?:\n>.*)*)', body, re.M)
            g = re.search(r'## Gotchas\n(.*?)(?:\n## |\Z)', body, re.S)
            notes.append({'path': rel, 'kind': fm.get('kind'), 'title': fm.get('title'), 'game': fm.get('game', ''), 'games_also': fm.get('games_also', []),
                          'game_version': fm.get('game_version', ''), 'platform': fm.get('platform'), 'engine': fm.get('engine'), 'route': fm.get('route'),
                          'tools': fm.get('tools', []), 'anti_cheat': fm.get('anti_cheat', ''), 'status': fm.get('status'), 'agents': fm.get('agents', []),
                          'date': fm.get('date'), 'tags': fm.get('tags', []) if isinstance(fm.get('tags'), list) else [],
                          'url': BASE + rel, 'summary': re.sub(r'\s*\n>\s*', ' ', summ.group(1)).strip()[:500] if summ else '',
                          'gotchas': len(re.findall(r'^\d+\.\s', g.group(1), re.M)) if g else 0, 'source': 'local'})
    notes.sort(key=lambda n: (n['kind'], n['path']))
    out = os.path.join(a.repo_root, 'skills', 'gamedecomp-library', 'data', 'local-notes.json')
    json.dump({'meta': {'source': 'https://github.com/madpai/game-decomp-compendium', 'license': 'MIT'}, 'notes': notes}, open(out, 'w'), indent=0, ensure_ascii=False)
    lines = ['# Field notes index', '', '_Generated by `skills/gamedecomp-library/scripts/refresh/index_local_notes.py`; do not edit by hand._', '', '| Kind | Note | Engine | Route | Status | Gotchas | Date |', '|---|---|---|---|---|---|---|']
    for n in notes: lines.append(f"| {n['kind']} | [{n['title']}]({n['path']}) | {n.get('engine') or ''} | {n.get('route') or ''} | {n['status']} | {n['gotchas']} | {n['date']} |")
    open(os.path.join(kd, 'INDEX.md'), 'w').write('\n'.join(lines) + '\n')
    print(f'{len(notes)} notes indexed', ('; PROBLEMS:\n  ' + '\n  '.join(bad)) if bad else '')
    sys.exit(1 if bad else 0)

if __name__ == '__main__': main()
