#!/usr/bin/env python3
"""Regenerate references/platform-playbook.md from the compendium catalog (what each platform's projects actually use).
usage: gen_platform_playbook.py [--out FILE]   (reads gamedecomp-library/data/catalog.json, local copy or downloaded)"""
import argparse, collections, json, os, statistics, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', 'gamedecomp-library', 'scripts'))
from common import load

ORDER = ['Windows PC', 'DOS', 'Xbox', 'Xbox 360', 'PlayStation', 'PlayStation 2', 'PlayStation Portable', 'GameCube', 'Wii', 'Nintendo 64', 'Nintendo DS', 'Nintendo 3DS', 'Game Boy Advance', 'Game Boy', 'SNES', 'NES', 'Switch', 'Dreamcast', 'Saturn']
def plat(e):
    p = (e['platform'] or '').replace(' (derived)', '')
    pl = p.lower()
    for k, v in (('playstation 2', 'PlayStation 2'), ('playstation portable', 'PlayStation Portable'), ('playstation', 'PlayStation'), ('gamecube', 'GameCube'), ('wii', 'Wii'), ('nintendo 64', 'Nintendo 64'), ('nintendo ds', 'Nintendo DS'),
                 ('nintendo 3ds', 'Nintendo 3DS'), ('game boy advance', 'Game Boy Advance'), ('game boy', 'Game Boy'), ('switch', 'Switch'), ('xbox 360', 'Xbox 360'), ('xbox', 'Xbox'), ('dreamcast', 'Dreamcast'), ('saturn', 'Saturn'),
                 ('snes', 'SNES'), ('nes', 'NES'), ('dos', 'DOS'), ('windows', 'Windows PC')):
        if k in pl: return v
    return None

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--out', default=os.path.join(HERE, '..', 'references', 'platform-playbook.md')); a = ap.parse_args()
    rows = [e for e in load('catalog.json') if e['category'] == 'decomp']
    by = collections.defaultdict(list)
    for e in rows:
        p = plat(e)
        if p: by[p].append(e)
    out = ['# Platform playbook (computed from the catalog)', '',
           f'Generated by `scripts/gen_platform_playbook.py` from {len(rows)} decomp entries; platform for list-sourced entries is derived from README keywords and can be wrong. Counts are projects whose README mentions the tool; treat as a prior for "what do projects on this platform use", then read two exemplar repos.', '']
    for p in ORDER:
        rs = by.get(p)
        if not rs: continue
        tc = collections.Counter(t for r in rs for t in r['tools'] if t not in ('discord', 'python', 'assets-extract', 'sha1', 'progress-report'))
        cc = collections.Counter(c for r in rs for c in r['compilers'])
        bc = collections.Counter(b for r in rs for b in r['build'] if b not in ('ci', 'docs/', 'src/', 'include/', 'tools/', 'config/'))
        prog = [r['progress'] for r in rs if r['progress'] not in (None, '')]
        lic = collections.Counter(r['license'] or 'none' for r in rs)
        ex = sorted([r for r in rs if r['progress'] not in (None, '')], key=lambda r: (-(r['progress'] or 0), -(r['stars'] or 0)))[:3] + sorted(rs, key=lambda r: -(r['stars'] or 0))[:2]
        seen = []; [seen.append(r) for r in ex if r not in seen]
        out += [f'## {p} ({len(rs)} projects' + (f', median reported progress {statistics.median(prog):.0f}%' if prog else '') + ')',
                '- Tools in READMEs: ' + (', '.join(f'{k} ({v})' for k, v in tc.most_common(9)) or 'n/a'),
                '- Compilers mentioned: ' + (', '.join(f'{k} ({v})' for k, v in cc.most_common(5)) or 'n/a'),
                '- Build styles: ' + (', '.join(f'{k} ({v})' for k, v in bc.most_common(6)) or 'n/a'),
                '- Licences: ' + ', '.join(f'{k} ({v})' for k, v in lic.most_common(4)),
                '- Exemplars: ' + '; '.join(f"{r['name']} [{r['url'].split('github.com/')[-1]}]" for r in seen[:5]), '']
    out += ['## How to read this', '- `objdiff` + `ninja configure.py` + `wibo` dominates GameCube/Wii/Xbox 360 (dtk-template lineage); `splat` + `make` + `asm-differ`/`decomp-permuter` dominates N64/PS1/PS2/GBA; Windows PC projects split between `reccmp` (annotated source) and dtk/objdiff configurations; Switch uses clang with cmake.',
            '- Progress medians are not comparable across platforms (GBA/N64/PS1 are small games and often 100%; PS2/Wii/Switch are large).',
            '- To dig deeper: `python3 <gamedecomp-library>/scripts/query.py --platform "<name>" --min-progress 50 --sort progress`.']
    open(a.out, 'w').write('\n'.join(out) + '\n'); print('wrote', a.out, len(out), 'lines')

if __name__ == '__main__': main()
